name: Pain-Au-Chocolat
on: [push, delete]
env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-DOP-200-NAN-2-1-bschocolatine-louis.barreteau.git
on:
  push:
    branches-ignore:
      - ga-ignore-**
  pull_request:
    branches-ignore:
      - ga-ignore-**
jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          #!/bin/bash
          UNWANTED_FILES=("#**" "**#" "**.a" "**~" "pain_au_chocolat" "**.o" "**.a" "**.so" "**.gcno" "**.gcda" "**.gcov" "/tmp")
          ERRORS=0

          for FILE in ${UNWANTED_FILES[*]}
          do
              NOM_VAR=$(find -type f -iname $FILE)
              if [ $NOM_VAR ]
              then
                  ((ERRORS = 1))
                  echo "::error title="Unwanted file detected:$NOM_VAR"::$NOM_VAR"
              fi
          done
          if [ $ERRORS = 1 ]
          then
              echo "::error title="Checks if the repository is clean and void of any unwanted files(temp files, binary, etc.)"::edd"
          fi
  cloning_repository:
    needs: check_repository_cleanliness
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/B-MUL-200-NAN-2-1-myrpg-julien.renard.git
          ssh_private_key:
            ${{ secrets.SYNC_REPO_KEY }}